[package]
name = "rcsplit"
version = "0.1.0"
authors = ["Murtaza Akbari <murtazasakbari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
regex = "1"